// ═══════════════════════════════════════════════════════════════════════
//  PUBLIC COMPANIES (financial data from Q4 2025 / Q3 FY2026 earnings)
// ═══════════════════════════════════════════════════════════════════════
export const COMPANIES = {
  VRT: { tier:"direct", ticker:"VRT", name:"Vertiv Holdings", price:240.60, mcap:92.9, pe_fwd:40.0, fy26e_rev:13.5, fy26e_eps:6.02, fy26e_growth:28, op_margin:22.5, dc_pct:75, lc_growth:"+100%", backlog:"$15B", color:"#818cf8", role:"Power & Cooling Infrastructure", summary:"Pure-play DC infrastructure leader. NVIDIA co-dev partner for GB200 reference architectures. $15B backlog, 2.9x book-to-bill. Liquid cooling rev 2x YoY." },
  MOD: { tier:"direct", ticker:"MOD", name:"Modine Manufacturing", price:199.48, mcap:10.4, pe_fwd:44.3, fy26e_rev:3.15, fy26e_eps:4.50, fy26e_growth:22, op_margin:14.9, dc_pct:35, lc_growth:"+78%", backlog:"Record", color:"#34d399", role:"Chillers & Climate Solutions", summary:"DC revenue +78% YoY. Spinning off PT segment to become pure-play climate. $2B DC rev target by FY28. Commissioning new chiller lines in MO, MS, TX." },
  ETN: { tier:"direct", ticker:"ETN", name:"Eaton Corporation", price:347.00, mcap:137.8, pe_fwd:26.2, fy26e_rev:27.0, fy26e_eps:13.25, fy26e_growth:8, op_margin:24.0, dc_pct:18, lc_growth:"+200%", backlog:"$15.3B", color:"#f59e0b", role:"Power Management + Liquid Cooling", summary:"DC orders +200% YoY. Boyd Thermal acquisition ($9.5B, closing Q2 '26) adds $1.5B liquid cooling. Chip-to-grid solution. Mobility spin-off planned." },
  NVT: { tier:"direct", ticker:"NVT", name:"nVent Electric", price:116.05, mcap:19.2, pe_fwd:36.5, fy26e_rev:4.36, fy26e_eps:3.18, fy26e_growth:12, op_margin:22.0, dc_pct:30, lc_growth:"+50%", backlog:"Growing", color:"#06b6d4", role:"Enclosures & Thermal Management", summary:"Siemens collaboration on hyperscale cooling+power architectures. Modular LC platform launch. ~30% DC exposure, highest among diversified players." },
  SMCI: { tier:"direct", ticker:"SMCI", name:"Super Micro Computer", price:33.39, mcap:20.0, pe_fwd:11.9, fy26e_rev:40.0, fy26e_eps:2.80, fy26e_growth:70, op_margin:5.8, dc_pct:95, lc_growth:"+110%", backlog:"Expanding", color:"#f472b6", role:"AI Servers with Integrated DLC", summary:"DLC servers are the product — 98% heat capture. Raised FY26 rev guidance to $40B+. Blackwell 4U/2-OU liquid-cooled systems. Fastest to market." },
  SBGSY: { tier:"direct", ticker:"SBGSY", name:"Schneider Electric", price:265.0, mcap:155.0, pe_fwd:30.0, fy26e_rev:40.0, fy26e_eps:8.80, fy26e_growth:10, op_margin:18.5, dc_pct:22, lc_growth:"+60%", backlog:"Strong", color:"#a78bfa", role:"End-to-End DC Infrastructure", summary:"Acquired Motivair for liquid cooling portfolio. Full-stack DC infrastructure: power, cooling, software. Galaxy UPS line for hyperscale." },
  NVDA: { tier:"direct", ticker:"NVDA", name:"NVIDIA", price:131.0, mcap:3220.0, pe_fwd:28.5, fy26e_rev:200.0, fy26e_eps:4.60, fy26e_growth:55, op_margin:62.0, dc_pct:88, lc_growth:"N/A", backlog:"$30B+", color:"#76b900", role:"GPUs / AI Accelerators", summary:"GB200 NVL72 platform driving liquid cooling demand. 700W/chip thermal load. DC revenue $35.6B Q4 (+93% YoY). Rubin platform 2027." },
  ORCL: { tier:"direct", ticker:"ORCL", name:"Oracle", price:172.0, mcap:480.0, pe_fwd:25.0, fy26e_rev:66.0, fy26e_eps:6.90, fy26e_growth:15, op_margin:30.0, dc_pct:35, lc_growth:"N/A", backlog:"$130B RPO", color:"#f43f5e", role:"Cloud Infrastructure / DC Developer", summary:"Building Stargate campuses. $300B+ OpenAI deal over 5 years. Purchasing 400K GB200 chips for Abilene. $130B remaining performance obligations." },
  AMZN: { tier:"direct", ticker:"AMZN", name:"Amazon/AWS", price:225.0, mcap:2380.0, pe_fwd:32.0, fy26e_rev:700.0, fy26e_eps:7.00, fy26e_growth:12, op_margin:11.0, dc_pct:18, lc_growth:"N/A", backlog:"Large", color:"#ff9900", role:"Hyperscaler / DC Operator", summary:"Project Rainier for Anthropic ($11B). AWS Generative AI Innovation Center. $100B+ in DC expansion. Trainium 2 custom chips." },
  META: { tier:"direct", ticker:"META", name:"Meta Platforms", price:700.0, mcap:1780.0, pe_fwd:24.0, fy26e_rev:195.0, fy26e_eps:29.0, fy26e_growth:16, op_margin:35.0, dc_pct:12, lc_growth:"N/A", backlog:"$65B capex guide", color:"#0668E1", role:"Hyperscaler / DC Operator", summary:"Prometheus (1 GW, OH), Hyperion (5 GW, LA). $65B capex guidance 2025. Entering electricity trading. 30th DC broke ground in WI." },
  MSFT: { tier:"direct", ticker:"MSFT", name:"Microsoft", price:412.0, mcap:3060.0, pe_fwd:30.0, fy26e_rev:280.0, fy26e_eps:13.70, fy26e_growth:14, op_margin:44.0, dc_pct:15, lc_growth:"N/A", backlog:"$298B RPO", color:"#00a4ef", role:"Hyperscaler / DC Operator", summary:"131 DCs operational, 111 under construction. AI Superfactory in Atlanta. $20B PA investment. Sidekick liquid cooling for Azure Maia chips." },
  // ── New vendors & hyperscalers (Feb 2026) ──────────────────────────
  ANET: { tier:"direct", ticker:"ANET", name:"Arista Networks", price:132.79, mcap:178.3, pe_fwd:43.0, fy26e_rev:11.25, fy26e_eps:3.41, fy26e_growth:25, op_margin:46.0, dc_pct:70, lc_growth:"N/A", backlog:"N/A", color:"#e06666", role:"DC Networking Switches", summary:"Dominant in 400G/800G Ethernet for AI clusters. 2026 revenue guidance raised to 25% growth (~$11.25B), with $3.25B AI data center networking target. Operating margins ~46%, best-in-class among networking peers." },
  AVGO: { tier:"direct", ticker:"AVGO", name:"Broadcom", price:332.65, mcap:1570.0, pe_fwd:32.9, fy26e_rev:81.0, fy26e_eps:9.39, fy26e_growth:27, op_margin:66.0, dc_pct:55, lc_growth:"N/A", backlog:"$73B AI backlog", color:"#b91c1c", role:"Custom AI Chips & Networking ASICs", summary:"AI semiconductor revenue doubling YoY to $8.2B/quarter. $73B AI backlog across custom XPUs and Ethernet switches for hyperscalers. Non-GAAP operating margin 66%, with VMware software providing durable recurring revenue base." },
  PWR: { tier:"direct", ticker:"PWR", name:"Quanta Services", price:436.00, mcap:61.6, pe_fwd:33.2, fy26e_rev:33.5, fy26e_eps:13.00, fy26e_growth:18, op_margin:8.5, dc_pct:10, lc_growth:"N/A", backlog:"$44B", color:"#e69138", role:"Electrical Construction & Grid Infrastructure", summary:"Largest US electrical contractor building transmission lines and substations feeding data centers. $44B total backlog with DC as fastest-growing segment. Key beneficiary of grid buildout required for multi-GW AI campuses." },
  GLW: { tier:"direct", ticker:"GLW", name:"Corning", price:139.51, mcap:114.5, pe_fwd:31.5, fy26e_rev:18.7, fy26e_eps:3.08, fy26e_growth:20, op_margin:20.0, dc_pct:40, lc_growth:"N/A", backlog:"$6B Meta deal", color:"#f1c232", role:"Fiber Optic Cable & Connectivity", summary:"$6B Meta fiber-optic supply deal through 2030 anchors DC growth. Optical Communications segment grew 35% to $6.3B in 2025, with enterprise/DC sales up 61%. Springboard plan targets $4B+ in incremental annualized sales by end of 2026." },
  FIX: { tier:"direct", ticker:"FIX", name:"Comfort Systems USA", price:1462.00, mcap:51.6, pe_fwd:41.5, fy26e_rev:10.6, fy26e_eps:35.20, fy26e_growth:16, op_margin:14.4, dc_pct:45, lc_growth:"N/A", backlog:"$11.9B", color:"#c27ba0", role:"HVAC & Mechanical Contractor", summary:"Data center HVAC now 45% of revenue, up from 33% a year ago. Record $11.9B backlog doubled YoY. Q4 2025 EPS of $9.37 crushed estimates by 39%. Industrial supercycle in DC mechanical/electrical construction driving multi-year visibility." },
  GEV: { tier:"direct", ticker:"GEV", name:"GE Vernova", price:829.85, mcap:223.8, pe_fwd:48.4, fy26e_rev:44.5, fy26e_eps:13.95, fy26e_growth:12, op_margin:11.0, dc_pct:15, lc_growth:"N/A", backlog:"$59.3B orders", color:"#674ea7", role:"Gas Turbines & Grid Solutions", summary:"Provides 25% of world's power; critical enabler of behind-the-meter gas generation for data centers. Q4 2025 orders surged 65% YoY to $22.2B. 2026 revenue guided $44-45B with EBITDA margins of 11-13%." },
  CEG: { tier:"direct", ticker:"CEG", name:"Constellation Energy", price:294.84, mcap:104.5, pe_fwd:30.7, fy26e_rev:24.4, fy26e_eps:9.34, fy26e_growth:8, op_margin:16.3, dc_pct:20, lc_growth:"N/A", backlog:"Long-term PPAs", color:"#3c78d8", role:"Nuclear Power PPAs for DCs", summary:"Largest US nuclear fleet operator, signing long-term carbon-free PPAs with hyperscalers. Calpine acquisition (~$16.4B) adds natural gas capacity. Microsoft TMI restart deal established the template for nuclear-powered data centers." },
  CIEN: { tier:"direct", ticker:"CIEN", name:"Ciena", price:334.95, mcap:47.4, pe_fwd:50.8, fy26e_rev:5.9, fy26e_eps:5.25, fy26e_growth:24, op_margin:17.0, dc_pct:42, lc_growth:"N/A", backlog:"$5B", color:"#45818e", role:"Optical Networking & DCI", summary:"Data center interconnect demand surging as AI clusters scale across regions. FY2026 revenue guided to $5.7-6.1B with 17% adjusted operating margin. $5B backlog provides strong visibility. Direct cloud provider revenue 42% of total, growing 49% YoY." },
  EME: { tier:"direct", ticker:"EME", name:"EMCOR Group", price:803.55, mcap:26.0, pe_fwd:27.1, fy26e_rev:17.2, fy26e_eps:27.42, fy26e_growth:6, op_margin:9.3, dc_pct:25, lc_growth:"N/A", backlog:"$12.6B RPO", color:"#a64d79", role:"Electrical & Mechanical DC Construction", summary:"Record backlog with Network & Communications RPO at $4.3B (+100% YoY), driven by data center electrical/mechanical construction. 9.3% operating margins sustained despite project scale-up. Pure-play beneficiary of DC buildout cycle." },
  BE: { tier:"direct", ticker:"BE", name:"Bloom Energy", price:147.51, mcap:41.5, pe_fwd:107.0, fy26e_rev:3.2, fy26e_eps:1.38, fy26e_growth:52, op_margin:11.3, dc_pct:45, lc_growth:"N/A", backlog:"$20B total", color:"#7cb342", role:"On-Site Fuel Cell Power for DCs", summary:"Product backlog surged 140% YoY to ~$6B as hyperscalers adopt solid-oxide fuel cells for behind-the-meter DC power. 2026 revenue guided to $3.1-3.3B (+52% YoY). Solving grid interconnection bottleneck for AI campuses." },
  LUMN: { tier:"direct", ticker:"LUMN", name:"Lumen Technologies", price:8.39, mcap:8.95, pe_fwd:"N/M", fy26e_rev:12.0, fy26e_eps:-0.26, fy26e_growth:-3, op_margin:-6.6, dc_pct:30, lc_growth:"N/A", backlog:"$13B PCF TCV", color:"#00b0f0", role:"Fiber Connectivity & Private Network Fabric", summary:"Secured ~$13B in Private Connectivity Fabric contracts with hyperscalers linking AI data centers. Turnaround play: negative margins today but $400-500M annual PCF revenue expected by 2028. Owns 500K+ route-miles of fiber critical for DC interconnection." },
  MRVL: { tier:"direct", ticker:"MRVL", name:"Marvell Technology", price:79.98, mcap:69.2, pe_fwd:23.0, fy26e_rev:8.0, fy26e_eps:2.84, fy26e_growth:40, op_margin:36.3, dc_pct:73, lc_growth:"N/A", backlog:"18 XPU sockets", color:"#e91e63", role:"Custom AI Chips & DC Interconnect", summary:"Data center is 73% of revenue with custom silicon engagements across all four major hyperscalers. AI revenue exceeding $2.5B in FY26. 18 multigenerational custom XPU sockets provide deep competitive moat and long-term revenue visibility." },
  JCI: { tier:"direct", ticker:"JCI", name:"Johnson Controls", price:143.79, mcap:88.0, pe_fwd:25.2, fy26e_rev:25.1, fy26e_eps:4.70, fy26e_growth:7, op_margin:13.2, dc_pct:15, lc_growth:"Growing", backlog:"$18B record", color:"#00897b", role:"DC Thermal Management & Building Controls", summary:"Record $18B backlog (+20% YoY) driven by multi-year data center and mission-critical facility projects. Acquired Alloy Enterprises to expand cooling portfolio. AI-driven HVAC optimization and chiller systems for hyperscale deployments." },
  CAT: { tier:"direct", ticker:"CAT", name:"Caterpillar", price:774.20, mcap:323.7, pe_fwd:30.0, fy26e_rev:71.5, fy26e_eps:22.50, fy26e_growth:6, op_margin:17.2, dc_pct:15, lc_growth:"N/A", backlog:"$51B (+71% YoY)", color:"#ffab00", role:"Backup Power Generators & Gas Turbines", summary:"Power generation sales exceeded $10B in 2025 (+30% YoY), driven by AI data center demand. Record $51B backlog includes a 2 GW natural gas genset order. Dominant in large reciprocating gensets for DC backup and prime power." },
  CMI: { tier:"direct", ticker:"CMI", name:"Cummins", price:593.28, mcap:80.5, pe_fwd:29.7, fy26e_rev:35.4, fy26e_eps:26.04, fy26e_growth:5, op_margin:11.2, dc_pct:10, lc_growth:"N/A", backlog:"Record PS backlog", color:"#d84315", role:"Backup Power Generators & Natural Gas Engines", summary:"Power Systems segment hit record $7.5B revenue with 22.7% EBITDA margin, powered by data center backup demand. 2026 power revenue guided +12-17%. Natural gas gensets increasingly preferred for DC prime power applications." },
  ABB: { tier:"direct", ticker:"ABB", name:"ABB", price:90.51, mcap:164.2, pe_fwd:27.5, fy26e_rev:35.5, fy26e_eps:3.60, fy26e_growth:7, op_margin:18.2, dc_pct:15, lc_growth:"N/A", backlog:"$25.3B record", color:"#ff1744", role:"Power Distribution & UPS Systems", summary:"Record $25.3B backlog with data centers driving very strong double-digit order growth in Electrification segment. Full-stack DC power offering: MV/LV switchgear, transformers, UPS, and power quality. 2026 guided for 6-9% revenue growth with margin expansion." },
  AMD: { tier:"direct", ticker:"AMD", name:"AMD", price:203.00, mcap:328.0, pe_fwd:30.6, fy26e_rev:46.8, fy26e_eps:6.64, fy26e_growth:35, op_margin:28.0, dc_pct:48, lc_growth:"N/A", backlog:"N/A", color:"#ed1c24", role:"GPUs & Server CPUs (Instinct/EPYC)", summary:"Record $16.6B DC revenue in FY2025 (+94% YoY) driven by Instinct MI300X/MI325X GPUs and EPYC server CPUs. EPYC Turin gaining hyperscaler share; MI350 launching mid-2026 to compete at NVIDIA's Blackwell tier." },
  COHR: { tier:"direct", ticker:"COHR", name:"Coherent", price:248.00, mcap:40.7, pe_fwd:31.6, fy26e_rev:6.8, fy26e_eps:5.20, fy26e_growth:22, op_margin:20.0, dc_pct:70, lc_growth:"N/A", backlog:"Strong", color:"#00bfff", role:"Optical Transceivers (800G/1.6T)", summary:"AI datacenter backbone supplier — 800G transceivers in mass production, 1.6T ramping across multiple hyperscale customers. DC&Comms revenue $1.2B/quarter (+34% YoY). Non-GAAP op margin expanding to ~20% as mix shifts toward higher-value AI networking." },
  TSLA: { tier:"direct", ticker:"TSLA", name:"Tesla", price:410.00, mcap:1370.0, pe_fwd:198.0, fy26e_rev:109.0, fy26e_eps:2.15, fy26e_growth:15, op_margin:7.2, dc_pct:13, lc_growth:"N/A", backlog:"Large", color:"#cc0000", role:"Battery Storage (Megapack)", summary:"Energy storage deployed 46.7 GWh in 2025 (+49% YoY), generating $12.8B revenue at 29.8% gross margin — nearly 2x auto margins. Megapack supplies DC campus backup and grid-scale storage. Sold $430M to Musk's xAI alone." },
  NEE: { tier:"direct", ticker:"NEE", name:"NextEra Energy", price:91.50, mcap:193.0, pe_fwd:22.7, fy26e_rev:30.0, fy26e_eps:4.00, fy26e_growth:10, op_margin:29.0, dc_pct:15, lc_growth:"N/A", backlog:"6 GW DC pipeline", color:"#00a651", role:"Renewables & Nuclear Power for DCs", summary:"Largest global generator of wind and solar energy. ~6 GW DC power pipeline in backlog, targeting 15-30 GW of DC power hubs by 2035. Exploring 6 GW of new nuclear at existing sites. Front-of-meter PPAs with hyperscalers for carbon-free power." },
  OWL: { tier:"direct", ticker:"OWL", name:"Blue Owl Capital", price:11.00, mcap:20.0, pe_fwd:15.4, fy26e_rev:3.2, fy26e_eps:0.80, fy26e_growth:13, op_margin:57.0, dc_pct:25, lc_growth:"N/A", backlog:"$34B infra capital", color:"#5c6bc0", role:"DC Infrastructure Financing", summary:"Alternative asset manager with $307B AUM. Closed $7B Digital Infrastructure Fund III (vs $4B target). Acquired IPI Partners adding 80+ global DCs and 1,000 design/build professionals. 58.5% FRE margin target for 2026." },
  GOOGL: { tier:"direct", ticker:"GOOGL", name:"Alphabet/Google", price:315.00, mcap:3810.0, pe_fwd:27.3, fy26e_rev:455.0, fy26e_eps:11.24, fy26e_growth:13, op_margin:32.0, dc_pct:17, lc_growth:"N/A", backlog:"$175-185B capex guide", color:"#4285f4", role:"Hyperscaler / DC Operator", summary:"Google Cloud at $70B annualized run rate (+48% YoY), operating margin surging to 30.1%. Guiding $175-185B capex in 2026 (~2x 2025) for AI infrastructure and DC expansion. TPU v6 Trillium custom chips for internal and Cloud workloads." },
  CRWV: { tier:"direct", ticker:"CRWV", name:"CoreWeave", price:88.00, mcap:46.5, pe_fwd:"N/M", fy26e_rev:12.0, fy26e_eps:-0.50, fy26e_growth:135, op_margin:-5.0, dc_pct:100, lc_growth:"N/A", backlog:"$56B contracted", color:"#7b2ff7", role:"GPU Cloud / DC Operator", summary:"Purpose-built GPU cloud with $56B contracted backlog and $50B RPO — fastest to $50B RPO in cloud history. Revenue tripling from ~$5.1B (2025) to ~$12B (2026E). 61% adjusted EBITDA margins but still GAAP-unprofitable due to massive capex." },
  VST: { tier:"direct", ticker:"VST", name:"Vistra", price:163.00, mcap:58.0, pe_fwd:16.1, fy26e_rev:18.5, fy26e_eps:8.82, fy26e_growth:8, op_margin:21.0, dc_pct:20, lc_growth:"N/A", backlog:"20yr Comanche Peak PPA", color:"#f7931e", role:"Nuclear & Gas Power Generation", summary:"Second-largest US nuclear fleet with 6 reactors / 6.4 GW. Signed 20-year, 1.2 GW PPA from Comanche Peak nuclear to serve DC load. 2026 adj. EBITDA guided $6.8-7.6B. Aggressive $3B+ buyback program underway." },
  TLN: { tier:"direct", ticker:"TLN", name:"Talen Energy", price:380.00, mcap:17.4, pe_fwd:20.8, fy26e_rev:3.5, fy26e_eps:20.51, fy26e_growth:50, op_margin:15.0, dc_pct:55, lc_growth:"N/A", backlog:"1.92 GW Amazon PPA", color:"#e63946", role:"Nuclear Power (Susquehanna)", summary:"Operates 90% of the 2.5 GW Susquehanna nuclear plant in PA — ground zero for DC power. Signed front-of-meter 1.92 GW PPA with Amazon through 2042 (~2x original deal). ~55% revenue now DC-linked." },
  // ── New companies (Feb 2026 expansion — direct tier) ─────────────────
  APLD: { tier:"direct", ticker:"APLD", name:"Applied Digital", price:30.00, mcap:8.4, pe_fwd:"N/M", fy26e_rev:1.2, fy26e_eps:-0.40, fy26e_growth:200, op_margin:-15.0, dc_pct:100, lc_growth:"N/A", backlog:"$11B contracted", color:"#26c6da", role:"GPU Cloud & DC Developer", summary:"Purpose-built AI DC operator. Polaris Forge 1 (400 MW) operational, Forge 2 (1 GW) and Delta Forge 1 (430 MW) in development. $2.35B Macquarie/Blue Owl financing. 100% DC pure-play pivoting from crypto mining." },
  EQIX: { tier:"direct", ticker:"EQIX", name:"Equinix", price:958.00, mcap:83.3, pe_fwd:"N/M", fy26e_rev:9.2, fy26e_eps:12.50, fy26e_growth:10, op_margin:18.0, dc_pct:100, lc_growth:"N/A", backlog:"$5.9B pipeline", color:"#e040fb", role:"DC REIT / Global Colocation", summary:"World's largest DC REIT with 270+ facilities across 73 metros. xScale JV with GIC/CPP for hyperscale expansion. AFFO/share ~$37. Oklo SMR and Bloom fuel cell power partnerships for behind-the-meter DC generation." },
  DLR: { tier:"direct", ticker:"DLR", name:"Digital Realty", price:177.00, mcap:59.6, pe_fwd:"N/M", fy26e_rev:6.2, fy26e_eps:7.20, fy26e_growth:8, op_margin:16.0, dc_pct:100, lc_growth:"N/A", backlog:"$7B Blackstone JV", color:"#ab47bc", role:"DC REIT / Hyperscale Developer", summary:"Second-largest DC REIT with 300+ facilities globally. Digital Dulles campus (7.5M sqft, Northern VA) and $7B Blackstone JV for hyperscale development. Core FFO/share ~$7.20. Record leasing driven by AI demand." },
  APH: { tier:"direct", ticker:"APH", name:"Amphenol", price:149.00, mcap:180.0, pe_fwd:33.5, fy26e_rev:22.0, fy26e_eps:4.45, fy26e_growth:20, op_margin:22.0, dc_pct:33, lc_growth:"+40%", backlog:"Strong", color:"#ff7043", role:"DC Connectors & Cable Assemblies", summary:"IT Datacom is 33% of revenue — high-speed I/O connectors, fiber-optic assemblies, and liquid cooling connectors for AI servers. Acquiring CommScope CCS division ($10.5B) adding structured cabling. $178B market cap, 20%+ organic growth." },
  LITE: { tier:"direct", ticker:"LITE", name:"Lumentum", price:594.00, mcap:45.4, pe_fwd:51.2, fy26e_rev:2.8, fy26e_eps:8.40, fy26e_growth:45, op_margin:22.0, dc_pct:65, lc_growth:"+287%", backlog:"Record", color:"#ffab40", role:"Laser Chips & Optical Transceivers", summary:"Cloud & Networking 65% of revenue. EML laser chips powering 800G/1.6T transceivers for DC interconnect. Stock +287% in 2025. Key supplier to transceiver OEMs serving hyperscale AI networking buildout." },
  PRY: { tier:"direct", ticker:"PRY", name:"Prysmian", price:20.00, mcap:27.6, pe_fwd:18.8, fy26e_rev:18.5, fy26e_eps:1.06, fy26e_growth:12, op_margin:10.5, dc_pct:20, lc_growth:"N/A", backlog:"€12B+", color:"#8d6e63", role:"Power & Fiber Cable Manufacturing", summary:"World's largest cable manufacturer. Acquired Encore Wire adding US copper wire capacity. Supplies power cables, fiber-optic cables, and specialty connectivity for DC construction and grid interconnection." },
  HUBB: { tier:"direct", ticker:"HUBB", name:"Hubbell", price:487.00, mcap:27.9, pe_fwd:24.3, fy26e_rev:6.1, fy26e_eps:20.00, fy26e_growth:10, op_margin:24.0, dc_pct:15, lc_growth:"N/A", backlog:"Growing", color:"#4db6ac", role:"Electrical Distribution & DC Power", summary:"Double-digit DC organic growth. DMC Power acquisition ($825M) adds custom busbar and power distribution for hyperscale DCs. Electrical Solutions segment provides switchgear, transformers, and connectors for DC construction." },
  POWL: { tier:"direct", ticker:"POWL", name:"Powell Industries", price:594.00, mcap:5.5, pe_fwd:23.9, fy26e_rev:1.3, fy26e_eps:24.80, fy26e_growth:25, op_margin:20.0, dc_pct:25, lc_growth:"N/A", backlog:"$1.6B record", color:"#aed581", role:"Switchgear & Power Control Systems", summary:"Switchgear pure-play with ~25% DC revenue. Record $1.6B backlog driven by data center and utility switchgear demand. Custom medium-voltage switchgear and power control rooms for hyperscale DC substations." },
  LGRDY: { tier:"direct", ticker:"LGRDY", name:"Legrand", price:30.00, mcap:35.0, pe_fwd:25.0, fy26e_rev:9.5, fy26e_eps:1.20, fy26e_growth:8, op_margin:18.0, dc_pct:26, lc_growth:"N/A", backlog:"Growing", color:"#ba68c8", role:"DC Power Distribution & Rack Infrastructure", summary:"~26% of group revenue from DC segment via Server Technology (intelligent PDUs), Raritan (KVM/DCIM), and Starline (busway). Portfolio covers rack PDUs to building-level power distribution. ADR-listed." },
  OKLO: { tier:"direct", ticker:"OKLO", name:"Oklo", price:68.00, mcap:10.4, pe_fwd:"N/M", fy26e_rev:"N/A", fy26e_eps:"N/A", fy26e_growth:"N/A", op_margin:"N/A", dc_pct:100, lc_growth:"N/A", backlog:"1.7 GW pipeline", color:"#ffd54f", role:"Microreactor Developer (Nuclear)", summary:"Pre-revenue advanced fission company with 1.7 GW customer pipeline. 1.2 GW Meta deal, 500 MW Equinix deal, 750 MW RPower deal. Aurora powerhouse design targeting NRC approval. Sam Altman-backed." },
  SMR: { tier:"direct", ticker:"SMR", name:"NuScale Power", price:12.50, mcap:3.8, pe_fwd:"N/M", fy26e_rev:"N/A", fy26e_eps:"N/A", fy26e_growth:"N/A", op_margin:"N/A", dc_pct:100, lc_growth:"N/A", backlog:"6 GW framework", color:"#81d4fa", role:"Small Modular Reactor Designer", summary:"Only NRC-certified SMR design (VOYGR). 6 GW TVA framework agreement for SMR deployment at existing nuclear sites. Standard Power partnership for DC-dedicated SMR sites in OH and PA. Pre-revenue, targeting first deployment ~2030." },
  CLS: { tier:"direct", ticker:"CLS", name:"Celestica", price:293.00, mcap:33.8, pe_fwd:39.4, fy26e_rev:14.0, fy26e_eps:7.43, fy26e_growth:30, op_margin:9.0, dc_pct:72, lc_growth:"+60%", backlog:"Strong", color:"#4fc3f7", role:"DC Network Switches & Server Hardware", summary:"72-75% DC revenue. 41% market share in 200G+ Ethernet switches (white-box for hyperscalers). Rack-level CDUs for liquid cooling. Revenue growing 30%+ driven by AI networking and compute hardware demand." },
  STRL: { tier:"direct", ticker:"STRL", name:"Sterling Infrastructure", price:436.00, mcap:9.5, pe_fwd:33.6, fy26e_rev:2.3, fy26e_eps:13.00, fy26e_growth:18, op_margin:14.0, dc_pct:30, lc_growth:"+125%", backlog:"Growing", color:"#dce775", role:"DC Site Development & Civil Construction", summary:"E-Infrastructure Solutions segment focused on DC site development. Q3 2025 DC revenues +125% YoY. Site prep, foundations, and civil construction for hyperscale campuses across TX, VA, and Southeast." },
  FLEX: { tier:"direct", ticker:"FLEX", name:"Flex Ltd", price:64.00, mcap:23.6, pe_fwd:17.7, fy26e_rev:27.0, fy26e_eps:3.60, fy26e_growth:12, op_margin:6.5, dc_pct:25, lc_growth:"N/A", backlog:"Growing", color:"#90a4ae", role:"Modular DC Components & Rack CDUs", summary:"~25% DC revenue via Reliability Solutions segment. Manufactures modular DC components, rack-level CDUs, and power assemblies. Anord Mardix subsidiary provides critical power distribution for hyperscale DCs." },
  // ── New companies (Feb 2026 expansion — upstream tier) ───────────────
  FCX: { tier:"upstream", ticker:"FCX", name:"Freeport-McMoRan", price:65.00, mcap:93.4, pe_fwd:22.4, fy26e_rev:26.0, fy26e_eps:2.90, fy26e_growth:15, op_margin:30.0, dc_pct:"N/A", lc_growth:"N/A", backlog:"N/A", color:"#ef6c00", role:"Copper Producer (DC Supply Chain)", summary:"World's largest publicly traded copper producer. Each MW of DC capacity requires 27-33 tonnes of copper for power distribution, busbars, cabling, and cooling systems. Pure commodity exposure to DC buildout cycle." },
  NUE: { tier:"upstream", ticker:"NUE", name:"Nucor", price:179.00, mcap:40.9, pe_fwd:13.7, fy26e_rev:34.0, fy26e_eps:13.10, fy26e_growth:5, op_margin:12.0, dc_pct:"N/A", lc_growth:"N/A", backlog:"N/A", color:"#66bb6a", role:"Steel Producer (DC Construction)", summary:"#1 US steel producer and recycler. Structural steel, rebar, and steel decking consumed in massive quantities for DC construction. Hyperscale campuses require thousands of tons of structural steel per building." },
  STLD: { tier:"upstream", ticker:"STLD", name:"Steel Dynamics", price:206.00, mcap:29.4, pe_fwd:14.5, fy26e_rev:18.0, fy26e_eps:14.20, fy26e_growth:3, op_margin:13.0, dc_pct:"N/A", lc_growth:"N/A", backlog:"N/A", color:"#78909c", role:"Steel & Flat Roll Products", summary:"Third-largest US EAF steelmaker. Flat roll products used in DC structural framing, cladding, and equipment enclosures. Sinton TX flat roll mill positioned near growing TX DC corridor." },
  CC: { tier:"upstream", ticker:"CC", name:"Chemours", price:17.00, mcap:1.9, pe_fwd:9.4, fy26e_rev:5.8, fy26e_eps:1.80, fy26e_growth:10, op_margin:10.0, dc_pct:"N/A", lc_growth:"N/A", backlog:"N/A", color:"#ce93d8", role:"Refrigerants & Immersion Cooling Fluids", summary:"Opteon low-GWP refrigerants used in DC HVAC and precision cooling. Developing engineered immersion cooling fluids for direct-to-chip applications. TT segment provides thermal management solutions for electronics." },
};

// ═══════════════════════════════════════════════════════════════════════
//  DATA CENTER PROJECTS with linked companies
// ═══════════════════════════════════════════════════════════════════════
export const PROJECTS = [
  { id:1, name:"Stargate I — Abilene", state:"TX", lat:32.45, lng:-99.73, capacity:"1.2 GW", investment:"$100B+", status:"Under Construction", year:2026, type:"AI Training", operator:"OpenAI", elecRate:7.2,
    companies: [
      { ticker:"ORCL", role:"DC Developer & Cloud Provider", detail:"Building campus, purchasing 400K GB200 chips, $300B+ 5yr deal" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"GB200 NVL72 platform, 700W/chip requiring liquid cooling" },
      { ticker:"AMD", role:"GPU Supplier (Instinct)", detail:"AMD–OpenAI 6 GW strategic partnership (Oct 2025). Instinct MI450 deployment beginning H2 2026 alongside NVIDIA GB200" },
      { ticker:"VRT", role:"Power & Cooling Infrastructure", detail:"NVIDIA co-dev partner, 360AI platform, CDUs and liquid cooling" },
      { ticker:"SMCI", role:"AI Server Systems", detail:"Blackwell-ready DLC server racks, 98% heat capture" },
      { ticker:"ETN", role:"Power Distribution", detail:"UPS, switchgear, busbar. Boyd acquisition adds liquid cooling" },
      { ticker:"JCI", role:"Thermal Management & Building Controls", detail:"Silent-Aire custom air handlers and YORK chillers for multi-building campus. OpenBlue BMS platform" },
      { ticker:"STRL", role:"Site Development", detail:"E-Infrastructure Solutions for site preparation, foundations, and civil construction at 1,200+ acre Abilene campus" },
      { ticker:"APH", role:"High-Speed Connectors", detail:"I/O connectors, fiber-optic assemblies, and liquid cooling connectors for 400K+ GPU AI training cluster" },
    ]},
  { id:2, name:"Stargate — New Mexico", state:"NM", lat:35.08, lng:-106.65, capacity:"800 MW", investment:"$40B", status:"Announced", year:2027, type:"AI Training", operator:"OpenAI/Oracle", elecRate:7.6,
    companies: [
      { ticker:"ORCL", role:"DC Developer", detail:"Oracle-built campus as part of 4.5 GW expansion" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Next-gen GPU deployment for training workloads" },
      { ticker:"VRT", role:"Thermal & Power", detail:"Expected to supply reference architecture cooling" },
      { ticker:"SBGSY", role:"Electrical Infrastructure", detail:"Galaxy UPS, power distribution for hyperscale" },
    ]},
  { id:3, name:"Stargate — Ohio", state:"OH", lat:40.45, lng:-83.1, capacity:"600 MW", investment:"$30B", status:"Announced", year:2027, type:"AI Training", operator:"OpenAI/SoftBank", elecRate:7.9,
    companies: [
      { ticker:"ORCL", role:"DC Developer", detail:"Part of multi-state Stargate expansion" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Blackwell and next-gen platform deployment" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Liquid cooling CDUs, SmartRun prefab solutions" },
      { ticker:"ETN", role:"Power Infrastructure", detail:"Electrical Americas segment, power management" },
    ]},
  { id:4, name:"Stargate — Wisconsin (Lighthouse)", state:"WI", lat:43.78, lng:-88.26, capacity:"600 MW", investment:"$30B", status:"Under Construction", year:2028, type:"AI Training", operator:"Oracle/Vantage", elecRate:9.3,
    companies: [
      { ticker:"ORCL", role:"DC Developer & Operator", detail:"Partnership with Vantage, 'Lighthouse' project" },
      { ticker:"VRT", role:"Power & Cooling", detail:"MegaMod HDX up to 10MW, rack densities 50-100kW+" },
      { ticker:"MOD", role:"Chillers & HVAC", detail:"New Franklin, WI facility producing AHUs and modular DC units" },
      { ticker:"NVT", role:"Enclosures & Thermal", detail:"Rack enclosures, cable management, cooling solutions" },
    ]},
  { id:5, name:"Project Rainier", state:"IN", lat:39.95, lng:-86.4, capacity:"2.2 GW", investment:"$11B", status:"Under Construction", year:2026, type:"AI Training", operator:"Amazon/Anthropic", elecRate:8.2,
    companies: [
      { ticker:"AMZN", role:"Developer & Operator", detail:"1,200 acres, 7 of 30 DCs built. Trainium 2 custom chips" },
      { ticker:"VRT", role:"Cooling & Power", detail:"Multi-megawatt cooling for hyperscale GPU clusters" },
      { ticker:"SBGSY", role:"Power Distribution", detail:"Schneider Galaxy UPS, busway, BMS software" },
      { ticker:"MOD", role:"Chilled Water Systems", detail:"Airedale chillers for high-density compute cooling" },
      { ticker:"LGRDY", role:"Rack PDUs & Busway", detail:"Server Technology intelligent PDUs and Starline busway for rack-level power distribution" },
      { ticker:"FLEX", role:"Modular DC Components", detail:"Anord Mardix critical power distribution and modular DC assemblies for phased 2.2 GW build" },
    ]},
  { id:6, name:"Mount Pleasant / Fairwater", state:"WI", lat:42.55, lng:-88.5, capacity:"900 MW", investment:"$7.3B", status:"Under Construction", year:2026, type:"AI Supercomputer", operator:"Microsoft", elecRate:9.3,
    companies: [
      { ticker:"MSFT", role:"Developer & Operator", detail:"315-acre campus, 1.2M sqft. 90% closed-loop liquid cooling. $7.3B total investment" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Massive GPU deployment for AI supercomputer cluster powering Azure AI" },
      { ticker:"VRT", role:"Cooling & Power Infrastructure", detail:"Liebert thermal systems, CDUs, rack PDUs for liquid-cooled AI racks" },
      { ticker:"ETN", role:"Power Distribution", detail:"UPS, medium-voltage switchgear, 120 miles underground cable distribution" },
      { ticker:"FIX", role:"Mechanical Contractor", detail:"HVAC and mechanical systems for second-largest water-cooled chiller plant on earth" },
      { ticker:"PWR", role:"Electrical Construction", detail:"Substation and grid interconnection for 900 MW peak demand from We Energies" },
    ]},
  { id:7, name:"Microsoft AI Superfactory (ATL)", state:"GA", lat:33.75, lng:-84.39, capacity:"400 MW", investment:"$3B", status:"Operational", year:2025, type:"AI Superfactory", operator:"Microsoft", elecRate:7.3,
    companies: [
      { ticker:"MSFT", role:"Developer & Operator", detail:"First AI superfactory, hundreds of thousands of GPUs" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Advanced GPU deployment for AI workloads" },
      { ticker:"AMD", role:"GPU & CPU Supplier", detail:"Instinct MI300X powers Azure OpenAI Service inference. EPYC Turin host CPUs in ND MI300X V5 VM instances" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Sidekick-class liquid cooling for Azure Maia chips" },
      { ticker:"ETN", role:"Power Management", detail:"Critical power distribution and protection" },
    ]},
  { id:8, name:"Prometheus", state:"OH", lat:39.72, lng:-82.55, capacity:"1 GW", investment:"$10B+", status:"Under Construction", year:2026, type:"AI Training", operator:"Meta", elecRate:7.9,
    companies: [
      { ticker:"META", role:"Developer & Operator", detail:"First gigawatt DC. 200MW on-site natural gas by Nov 2026" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Millions of AI chips in expanded NVIDIA deal" },
      { ticker:"AMD", role:"Server CPU Supplier (EPYC)", detail:"EPYC processors for custom OCP single-socket servers. Helios AI rack built on Meta's 2025 OCP design spec" },
      { ticker:"VRT", role:"Cooling & Power", detail:"Hyperscale thermal management, prefab modules" },
      { ticker:"MOD", role:"Precision Cooling", detail:"Chillers and CDUs for high-density AI racks" },
      { ticker:"COHR", role:"Optical Transceivers (800G/1.6T)", detail:"Meta is a confirmed hyperscale customer. 500K+ GPUs across buildings require massive intra-cluster optical connectivity" },
      { ticker:"VST", role:"Nuclear Power PPA", detail:"20-year, 1.2 GW PPA from Comanche Peak nuclear to serve Meta DC load" },
      { ticker:"OKLO", role:"Nuclear Microreactor Partnership", detail:"Part of 1.2 GW Meta-Oklo deal for advanced fission power at Meta DC campuses" },
    ]},
  { id:9, name:"Hyperion", state:"LA", lat:30.48, lng:-91.19, capacity:"5 GW", investment:"$50B+", status:"Planned", year:2028, type:"AI Mega Campus", operator:"Meta", elecRate:6.2,
    companies: [
      { ticker:"META", role:"Developer & Operator", detail:"Manhattan-sized. 10 DCs, 1,200 acres. 3 gas plants ($3B)" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Multi-million GPU deployment over build-out" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Largest potential single-site cooling deployment" },
      { ticker:"ETN", role:"Power + Liquid Cooling", detail:"Boyd liquid cooling + Eaton power from chip to grid" },
      { ticker:"SBGSY", role:"Building Management", detail:"EcoStruxure BMS, power monitoring" },
      { ticker:"MOD", role:"Large-Scale Chillers", detail:"Modular chiller systems for phased build-out" },
      { ticker:"JCI", role:"Thermal Management & Building Controls", detail:"Silent-Aire custom air handlers and YORK chillers for 10-building, 1,200-acre campus. Integrated BMS for phased 5 GW build" },
      { ticker:"OKLO", role:"Nuclear Microreactor Partnership", detail:"Part of 1.2 GW Meta-Oklo deal. Aurora microreactors for behind-the-meter power at 5 GW mega campus" },
    ]},
  { id:10, name:"Amazon Richmond County", state:"NC", lat:34.97, lng:-79.89, capacity:"500 MW", investment:"$10B", status:"Under Construction", year:2027, type:"Cloud/AI", operator:"Amazon/AWS", elecRate:7.5,
    companies: [
      { ticker:"AMZN", role:"Developer & Operator", detail:"20 buildings at full build-out, near Duke Energy 2.24GW plant" },
      { ticker:"VRT", role:"Cooling & Power", detail:"Thermal management for 200K+ sqft buildings" },
      { ticker:"SBGSY", role:"Power Distribution", detail:"Medium-voltage switchgear and UPS systems" },
    ]},
  { id:11, name:"Microsoft PA — Salem Township", state:"PA", lat:41.08, lng:-76.53, capacity:"800 MW", investment:"$20B", status:"Under Construction", year:2027, type:"Cloud/AI", operator:"Microsoft", elecRate:8.5,
    companies: [
      { ticker:"MSFT", role:"Developer & Operator", detail:"Adjacent to Susquehanna nuclear plant, direct power connection" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Pre-engineered AI cooling solutions" },
      { ticker:"ETN", role:"Power Distribution", detail:"Fibrebond modular power enclosures" },
      { ticker:"NVT", role:"Enclosures & Protection", detail:"IT rack systems and cable management" },
    ]},
  { id:12, name:"Anthropic/FluidStack TX", state:"TX", lat:30.27, lng:-97.74, capacity:"500 MW", investment:"$25B", status:"Announced", year:2027, type:"AI Training", operator:"Anthropic", elecRate:7.2,
    companies: [
      { ticker:"VRT", role:"Cooling & Power", detail:"Expected primary cooling infrastructure vendor" },
      { ticker:"SMCI", role:"AI Server Systems", detail:"Liquid-cooled server racks for training clusters" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Next-gen GPU deployment" },
      { ticker:"ETN", role:"Power Management", detail:"Electrical distribution and protection" },
    ]},
  { id:13, name:"Anthropic/FluidStack NY", state:"NY", lat:43.0, lng:-75.5, capacity:"500 MW", investment:"$25B", status:"Announced", year:2027, type:"AI Training", operator:"Anthropic", elecRate:14.8,
    companies: [
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management for training facility" },
      { ticker:"SMCI", role:"Server Infrastructure", detail:"DLC server systems" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"AI accelerator deployment" },
    ]},
  { id:14, name:"Colossus", state:"TN", lat:35.15, lng:-90.05, capacity:"150 MW", investment:"$3B", status:"Operational", year:2025, type:"AI Training", operator:"xAI", elecRate:7.6,
    companies: [
      { ticker:"NVDA", role:"GPU Supplier", detail:"100,000 H100 GPUs, built in 122 days" },
      { ticker:"SMCI", role:"Server Infrastructure", detail:"Rapid-deploy liquid-cooled server racks" },
      { ticker:"VRT", role:"Cooling Systems", detail:"CDUs and liquid cooling for dense GPU clusters" },
      { ticker:"TSLA", role:"Battery Storage (Megapack)", detail:"168 Megapacks providing 150 MW grid-tied battery backup. $430M in Megapack sales to xAI in 2025" },
    ]},
  { id:15, name:"Vantage Port Washington", state:"WI", lat:43.15, lng:-87.2, capacity:"1 GW", investment:"$15B", status:"Under Construction", year:2027, type:"Colocation", operator:"Vantage", elecRate:9.3,
    companies: [
      { ticker:"VRT", role:"Cooling & Power", detail:"Primary thermal and power infrastructure" },
      { ticker:"ETN", role:"Power Distribution", detail:"Switchgear, UPS, busbar systems" },
      { ticker:"MOD", role:"Chiller Systems", detail:"Climate Solutions segment products" },
      { ticker:"NVT", role:"Enclosures", detail:"Rack systems and protection solutions" },
    ]},
  { id:16, name:"Meta Beaver Dam", state:"WI", lat:43.80, lng:-89.3, capacity:"300 MW", investment:"$2B", status:"Under Construction", year:2026, type:"AI Training", operator:"Meta", elecRate:9.3,
    companies: [
      { ticker:"META", role:"Developer & Operator", detail:"30th data center, supporting AI and digital infra" },
      { ticker:"VRT", role:"Cooling", detail:"Thermal management systems" },
      { ticker:"MOD", role:"Chillers", detail:"Nearby Franklin WI facility supplying cooling units" },
    ]},
  { id:17, name:"Homer City GW Campus", state:"PA", lat:40.54, lng:-79.16, capacity:"4.5 GW", investment:"$30B+", status:"Under Construction", year:2028, type:"AI Mega Campus", operator:"Various", elecRate:8.5,
    companies: [
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Massive cooling deployment for 3,200-acre campus" },
      { ticker:"ETN", role:"Power + Cooling", detail:"Boyd liquid cooling + power distribution" },
      { ticker:"SBGSY", role:"Electrical Infrastructure", detail:"Medium/high voltage distribution" },
      { ticker:"MOD", role:"Industrial Cooling", detail:"Large-scale chiller systems for phased build" },
      { ticker:"NVT", role:"Protection Solutions", detail:"Enclosures and thermal management" },
      { ticker:"JCI", role:"Thermal Management & Building Controls", detail:"Silent-Aire CDUs and YORK chillers for multi-tenant 4.5 GW campus. Integrated BMS across 3,200 acres" },
      { ticker:"PRY", role:"Power & Fiber Cables", detail:"Power cables and fiber-optic infrastructure for 3,200-acre multi-GW campus phased build" },
      { ticker:"LGRDY", role:"Rack PDUs & Busway", detail:"Server Technology intelligent PDUs and Starline busway for rack-level power distribution across phased 4.5 GW build" },
    ]},
  // ── New projects (Feb 2026 expansion) ──────────────────────────────
  { id:18, name:"Union City Campus", state:"GA", lat:33.35, lng:-84.80, capacity:"324 MW", investment:"$1.8B", status:"Under Construction", year:2029, type:"Cloud/AI", operator:"Microsoft/EdgeConneX", elecRate:7.3,
    companies: [
      { ticker:"MSFT", role:"Anchor Tenant", detail:"Leasing 2.1M sqft hyperscale campus built to Microsoft specifications" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management systems for 3-phase, 612K sqft/building buildout" },
      { ticker:"ETN", role:"Power Management", detail:"UPS and power distribution for 324 MW phased capacity" },
      { ticker:"SBGSY", role:"Electrical Infrastructure", detail:"Galaxy UPS, medium-voltage distribution, EcoStruxure BMS" },
      { ticker:"EME", role:"Electrical & Mechanical Construction", detail:"DC electrical and mechanical systems installation across 136-acre site" },
      { ticker:"ABB", role:"Power Distribution & UPS", detail:"MV/LV switchgear and transformer systems for phased delivery" },
    ]},
  { id:19, name:"Three Mile Island PPA", state:"PA", lat:40.15, lng:-76.73, capacity:"835 MW", investment:"$1.6B", status:"Under Construction", year:2028, type:"Nuclear Power PPA", operator:"Microsoft/Constellation", elecRate:8.5,
    companies: [
      { ticker:"MSFT", role:"Power Offtaker", detail:"20-year PPA to match Azure DC power consumption across PJM Interconnection" },
      { ticker:"CEG", role:"Nuclear Plant Operator", detail:"Investing $1.6B to restart Unit 1 as Crane Clean Energy Center. $1B DOE loan secured" },
      { ticker:"GEV", role:"Turbine & Grid Equipment", detail:"Steam turbine refurbishment and grid interconnection equipment for 835 MW restart" },
      { ticker:"PWR", role:"Grid Infrastructure", detail:"Transmission line upgrades and substation work for nuclear-to-grid reconnection" },
      { ticker:"GLW", role:"Fiber Connectivity", detail:"Fiber-optic network linking TMI power output to Microsoft DC facilities in PA" },
      { ticker:"LUMN", role:"Private Connectivity Fabric", detail:"Dark fiber and network infrastructure connecting Microsoft DCs powered by TMI" },
    ]},
  { id:20, name:"Mattermeade Tech Campus", state:"VA", lat:38.15, lng:-77.52, capacity:"770 MW", investment:"$10B+", status:"Under Construction", year:2027, type:"Cloud/AI", operator:"Amazon/AWS", elecRate:7.8,
    companies: [
      { ticker:"AMZN", role:"Developer & Operator", detail:"1,143-acre campus, 11 two-story DC buildings. Part of $35B VA commitment by 2040" },
      { ticker:"VRT", role:"Cooling & Power Infrastructure", detail:"Thermal management for 770 MW phased high-density compute campus" },
      { ticker:"ETN", role:"Power Distribution", detail:"Three on-site substations, switchgear, UPS for 11-building campus" },
      { ticker:"SBGSY", role:"Power & Building Management", detail:"Medium-voltage distribution, EcoStruxure building management software" },
      { ticker:"CAT", role:"Backup Power Generators", detail:"Diesel genset backup power for mission-critical 770 MW campus" },
      { ticker:"ANET", role:"DC Networking", detail:"400G/800G Ethernet switches for AWS AI cluster interconnect" },
      { ticker:"STRL", role:"Site Development", detail:"E-Infrastructure Solutions for civil construction and site prep at 1,143-acre VA campus" },
    ]},
  { id:21, name:"Madison County Campus", state:"MS", lat:32.55, lng:-90.13, capacity:"500 MW", investment:"$16B", status:"Under Construction", year:2027, type:"Cloud/AI", operator:"Amazon/AWS", elecRate:7.1,
    companies: [
      { ticker:"AMZN", role:"Developer & Operator", detail:"Two complexes across 1,700 acres. Largest private investment in MS history. 1,000+ jobs" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"CDUs and thermal management for hyperscale campus in hot/humid climate" },
      { ticker:"ETN", role:"Power Management", detail:"UPS and power distribution systems for phased multi-GW buildout" },
      { ticker:"MOD", role:"Chiller Systems", detail:"Airedale chillers from nearby MS manufacturing facility" },
      { ticker:"PWR", role:"Electrical Construction", detail:"Substation construction and transmission infrastructure for remote mega-site" },
      { ticker:"CMI", role:"Backup Power Generators", detail:"Natural gas and diesel gensets for prime and backup power across two sites" },
    ]},
  { id:22, name:"Salem/Falls Townships", state:"PA", lat:41.45, lng:-76.0, capacity:"960 MW", investment:"$20B", status:"Under Construction", year:2028, type:"Cloud/AI", operator:"Amazon/AWS", elecRate:8.5,
    companies: [
      { ticker:"AMZN", role:"Developer & Operator", detail:"1,600-acre rezoned campus near Susquehanna nuclear. Largest private investment in PA history" },
      { ticker:"VRT", role:"Cooling & Power Infrastructure", detail:"Thermal management for nuclear-adjacent 15-building hyperscale campus" },
      { ticker:"ETN", role:"Power Distribution", detail:"Switchgear and UPS connecting nuclear-sourced power to DC loads" },
      { ticker:"ABB", role:"Power Distribution & Transformers", detail:"MV/LV switchgear and transformers for nuclear-to-DC power path" },
      { ticker:"TLN", role:"Nuclear Power Supplier", detail:"1,920 MW PPA through 2042 from Susquehanna plant. Original 960 MW campus acquired for $650M" },
      { ticker:"ANET", role:"DC Networking", detail:"High-speed Ethernet fabric for AWS AI and cloud workloads" },
    ]},
  { id:23, name:"Hermiston Campus", state:"OR", lat:45.84, lng:-119.29, capacity:"600 MW", investment:"$15B", status:"Operational", year:2025, type:"Cloud/AI", operator:"Amazon/AWS", elecRate:6.8,
    companies: [
      { ticker:"AMZN", role:"Developer & Operator", detail:"Part of $39.2B eastern OR investment since 2011. ~20 DCs across Umatilla/Morrow counties" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management for Columbia River-adjacent campus leveraging cool climate" },
      { ticker:"SBGSY", role:"Power Distribution", detail:"Medium-voltage switchgear and UPS systems for expanding campus" },
      { ticker:"CAT", role:"Backup Generators", detail:"104 diesel-fired 2.5 MW generators providing backup power across campus" },
      { ticker:"BE", role:"On-Site Fuel Cell Power", detail:"AWS deploying Bloom Energy solid-oxide fuel cells as primary power at OR data centers" },
      { ticker:"ANET", role:"DC Networking", detail:"High-bandwidth Ethernet switches for AWS US-West-2 region backbone" },
    ]},
  { id:24, name:"Stillwater Campus", state:"OK", lat:36.12, lng:-97.06, capacity:"500 MW", investment:"$3B", status:"Under Construction", year:2027, type:"Cloud/AI", operator:"Google", elecRate:6.5,
    companies: [
      { ticker:"GOOGL", role:"Developer & Operator", detail:"400-acre campus, six 300K sqft buildings. Part of $9B OK investment. OG&E power supply" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management systems for air-cooled AI data center campus" },
      { ticker:"ETN", role:"Power Distribution", detail:"Switchgear and UPS for phased 500 MW capacity across six buildings" },
      { ticker:"FIX", role:"HVAC & Mechanical Contractor", detail:"Advanced air-cooling HVAC systems for Oklahoma climate" },
      { ticker:"EME", role:"Electrical Construction", detail:"Electrical infrastructure installation for 6-building phased campus" },
      { ticker:"GLW", role:"Fiber Connectivity", detail:"Fiber-optic cabling and connectivity for campus interconnect and backhaul" },
    ]},
  { id:25, name:"Council Bluffs Expansion", state:"IA", lat:41.22, lng:-95.86, capacity:"1 GW", investment:"$7B", status:"Operational", year:2026, type:"Cloud/AI", operator:"Google", elecRate:7.0,
    companies: [
      { ticker:"GOOGL", role:"Developer & Operator", detail:"$7B expansion. Operating since 2009, $13.8B total invested in IA" },
      { ticker:"AVGO", role:"Custom AI Chip Co-Developer (TPU)", detail:"Co-designs every Google TPU generation with proprietary SerDes IP. Trillium/Ironwood silicon deployed at scale" },
      { ticker:"VRT", role:"Cooling & Power Infrastructure", detail:"Thermal management for expanding GW-scale campus with AI-dedicated capacity" },
      { ticker:"ETN", role:"Power Management", detail:"UPS and power distribution for phased expansion" },
      { ticker:"FIX", role:"HVAC & Mechanical Contractor", detail:"Mechanical systems and cooling for multi-building expansion" },
      { ticker:"CIEN", role:"Optical Networking & DCI", detail:"Data center interconnect optics linking Iowa campus to Google's global network" },
      { ticker:"GLW", role:"Fiber Optic Cable", detail:"Fiber infrastructure for campus interconnect and long-haul connectivity" },
    ]},
  { id:26, name:"Haskell County (Intersect)", state:"TX", lat:33.16, lng:-99.73, capacity:"600 MW", investment:"$10B", status:"Under Construction", year:2027, type:"Cloud/AI", operator:"Google", elecRate:7.2,
    companies: [
      { ticker:"GOOGL", role:"Developer & Operator", detail:"Part of $40B TX investment through 2027. Co-located with Intersect solar+BESS plant" },
      { ticker:"AVGO", role:"Custom AI Chip Co-Developer (TPU)", detail:"Broadcom co-develops Google Ironwood (TPU v7) reaching GA early 2026. Greenfield campus is among first large-scale Ironwood deployments" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Advanced air-cooling thermal systems for West Texas climate" },
      { ticker:"ETN", role:"Power Distribution", detail:"Switchgear connecting solar/BESS and grid power to DC loads" },
      { ticker:"PWR", role:"Electrical & Grid Infrastructure", detail:"Transmission lines and substation construction for remote TX site" },
      { ticker:"NEE", role:"Renewable Energy PPAs", detail:"Clean energy supply via long-term PPAs, part of Google's 6.2 GW TX renewable commitments" },
      { ticker:"TSLA", role:"Battery Storage (Megapack)", detail:"Google–Intersect 15.3 GWh Megapack supply contract through 2030. On-site BESS for renewable firming and DC backup" },
      { ticker:"CAT", role:"Backup Power Generators", detail:"Diesel and gas gensets for backup power at solar-paired campus" },
    ]},
  { id:27, name:"Meta Lebanon", state:"IN", lat:40.45, lng:-86.0, capacity:"1 GW", investment:"$10B", status:"Under Construction", year:2028, type:"AI Training", operator:"Meta", elecRate:8.2,
    companies: [
      { ticker:"META", role:"Developer & Operator", detail:"Broke ground Feb 2026. 1,500-acre LEAP district campus, 13 buildings, 4M sqft. Closed-loop liquid cooling" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Next-gen AI accelerators for Meta's training infrastructure" },
      { ticker:"VRT", role:"Power & Cooling Infrastructure", detail:"CDUs and thermal management for gigawatt-scale campus" },
      { ticker:"ETN", role:"Power Distribution", detail:"UPS, switchgear, and busbar for phased 1 GW build-out" },
      { ticker:"PWR", role:"Electrical Construction", detail:"Transmission lines and substation work for $120M utility infrastructure" },
      { ticker:"GLW", role:"Fiber Optic Connectivity", detail:"Part of $6B Meta fiber-optic supply deal through 2030" },
    ]},
  { id:28, name:"Meta Montgomery", state:"AL", lat:32.30, lng:-86.36, capacity:"300 MW", investment:"$1.5B", status:"Under Construction", year:2026, type:"AI Training", operator:"Meta", elecRate:7.8,
    companies: [
      { ticker:"META", role:"Developer & Operator", detail:"Off I-65 near Hyundai plant. 1.3M sqft across two buildings, nearly doubled from initial $800M" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"AI-optimized GPU deployment for latest Meta DC design" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management for LEED Gold certified facility" },
      { ticker:"FIX", role:"HVAC & Mechanical Contractor", detail:"Mechanical systems for 715K+ sqft AI-optimized data center" },
      { ticker:"GLW", role:"Fiber Optic Connectivity", detail:"Fiber infrastructure under multi-billion Meta supply agreement" },
    ]},
  { id:29, name:"Stargate Frontier — Texas", state:"TX", lat:32.95, lng:-99.15, capacity:"1.4 GW", investment:"$25B", status:"Under Construction", year:2027, type:"AI Training", operator:"Oracle/Vantage", elecRate:7.2,
    companies: [
      { ticker:"ORCL", role:"Cloud Infrastructure & Developer", detail:"Co-developer with Vantage. Part of 4.5 GW Stargate expansion for OpenAI" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"GB200 NVL72 platform deployment across 10 data center buildings" },
      { ticker:"VRT", role:"Power & Cooling Infrastructure", detail:"Liquid cooling CDUs for 3.7M sqft, 700-acre campus" },
      { ticker:"ETN", role:"Power Distribution", detail:"Switchgear and UPS systems for 1.4 GW phased energization" },
      { ticker:"PWR", role:"Electrical Construction & Grid", detail:"Transmission infrastructure connecting Shackelford County campus to ERCOT grid" },
      { ticker:"EME", role:"Electrical & Mechanical Construction", detail:"Large-scale DC electrical/mechanical build for 10-building campus" },
    ]},
  { id:30, name:"Stargate Michigan — The Barn", state:"MI", lat:42.17, lng:-83.78, capacity:"1.4 GW", investment:"$20B+", status:"Under Construction", year:2028, type:"AI Training", operator:"Oracle/Related Digital", elecRate:8.9,
    companies: [
      { ticker:"ORCL", role:"Cloud Infrastructure & Developer", detail:"Co-developer with Related Digital. Three 550K sqft buildings on 250 acres in Saline Township" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Next-gen AI accelerators for OpenAI Stargate workloads" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Closed-loop cooling systems limiting water use to office-building levels" },
      { ticker:"ABB", role:"Power Distribution & UPS", detail:"Medium-voltage switchgear and UPS for 1.4 GW DTE Energy supply" },
      { ticker:"EME", role:"Electrical & Mechanical Construction", detail:"Union construction workforce for 2,500+ construction jobs" },
      { ticker:"ANET", role:"DC Networking", detail:"High-bandwidth 400G/800G Ethernet switching for AI cluster interconnect" },
    ]},
  { id:31, name:"Stargate Lordstown", state:"OH", lat:41.17, lng:-80.87, capacity:"1.5 GW", investment:"$10B+", status:"Under Construction", year:2026, type:"AI Manufacturing & DC", operator:"SoftBank/Foxconn", elecRate:7.9,
    companies: [
      { ticker:"ORCL", role:"Cloud Infrastructure Partner", detail:"Oracle cloud integration as part of broader Stargate JV with OpenAI and SoftBank" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"AI accelerators for Stargate servers manufactured on-site by Foxconn" },
      { ticker:"VRT", role:"Power & Cooling Infrastructure", detail:"Thermal management for 6.2M sqft converted facility" },
      { ticker:"ABB", role:"Power Distribution", detail:"Switchgear and power quality systems for phased GW-scale energization" },
      { ticker:"PWR", role:"Grid Infrastructure", detail:"Transmission and substation upgrades to support 1.5 GW scaling" },
      { ticker:"CAT", role:"Backup Power Generation", detail:"Diesel and gas gensets for multi-GW campus backup power" },
      { ticker:"SMR", role:"Small Modular Reactor (Future)", detail:"NuScale-Standard Power partnership for DC-dedicated SMR sites in OH. Only NRC-certified SMR design" },
    ]},
  { id:32, name:"CoreWeave NEST", state:"NJ", lat:40.68, lng:-74.29, capacity:"250 MW", investment:"$1.8B", status:"Under Construction", year:2027, type:"GPU Cloud", operator:"CoreWeave", elecRate:11.5,
    companies: [
      { ticker:"CRWV", role:"Developer & Operator", detail:"Converted former Merck R&D building at NEST campus. $322M acquisition + $555M construction loan" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"High-density GPU deployment for CoreWeave's GPU cloud platform" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Liquid cooling CDUs for GPU-dense 392K sqft facility" },
      { ticker:"ETN", role:"Power Distribution", detail:"Critical power systems for 250 MW converted pharmaceutical campus" },
      { ticker:"ANET", role:"DC Networking", detail:"800G Ethernet fabric for GPU cloud interconnect" },
      { ticker:"COHR", role:"Optical Transceivers (800G)", detail:"800G pluggable transceivers behind Arista switches. One transceiver per switch port for GPU-dense fabric" },
      { ticker:"LITE", role:"Laser Chips (800G/1.6T)", detail:"EML laser chips powering 800G transceivers used in CoreWeave GPU cluster interconnect" },
      { ticker:"CLS", role:"Network Switches & Rack CDUs", detail:"White-box 200G+ Ethernet switches (41% market share) and rack-level CDUs for GPU-dense facility" },
    ]},
  { id:33, name:"CoreWeave Denton TX", state:"TX", lat:33.21, lng:-97.13, capacity:"260 MW", investment:"$1.2B", status:"Operational", year:2026, type:"GPU Cloud", operator:"CoreWeave/Core Scientific", elecRate:7.2,
    companies: [
      { ticker:"CRWV", role:"Operator & Tenant", detail:"16,000+ GPUs deployed by Jan 2026. 260 MW total contracted across 12-year leases worth $4.7B" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"Thousands of GPUs deployed for OpenAI compute workloads" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Liquid cooling for converted bitcoin mining facility" },
      { ticker:"ETN", role:"Power Management", detail:"Power distribution and protection for phased MW expansion" },
      { ticker:"ABB", role:"Power Distribution", detail:"Medium-voltage switchgear for site power conversion" },
      { ticker:"ANET", role:"DC Networking", detail:"High-speed Ethernet switching for GPU cluster fabric" },
      { ticker:"COHR", role:"Optical Transceivers (800G)", detail:"800G pluggable modules for 16,000+ GPU facility. DC&Comms revenue $1.2B/quarter (+34% YoY)" },
      { ticker:"LITE", role:"Laser Chips (800G)", detail:"EML laser chips powering 800G transceivers for CoreWeave/Core Scientific GPU cloud" },
      { ticker:"CLS", role:"Network Switches", detail:"White-box Ethernet switches for 16,000+ GPU cluster fabric. 41% market share in 200G+ switches" },
    ]},
  { id:34, name:"Polaris Forge 1", state:"ND", lat:46.00, lng:-98.52, capacity:"400 MW", investment:"$7B", status:"Operational", year:2025, type:"GPU Cloud", operator:"Applied Digital", elecRate:8.1,
    companies: [
      { ticker:"APLD", role:"Developer & Operator", detail:"Purpose-built AI factory. Three buildings, 400 MW. Proprietary waterless closed-loop cooling system" },
      { ticker:"CRWV", role:"Anchor Tenant", detail:"400 MW fully contracted under ~15-year leases. $11B total anticipated revenue" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"High-density GPU clusters for CoreWeave cloud compute" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Liquid cooling CDUs leveraging North Dakota's cool climate for near-zero water consumption" },
      { ticker:"ABB", role:"Power Distribution & UPS", detail:"HiPerGuard medium-voltage UPS and advanced MV switchgear" },
      { ticker:"CAT", role:"Backup Power Generation", detail:"Standby diesel generators for three-building, 400 MW campus" },
      { ticker:"OWL", role:"Infrastructure Financing", detail:"Macquarie/Blue Owl financing structure for AI factory buildout" },
    ]},
  { id:35, name:"Meridian Campus", state:"MS", lat:32.38, lng:-88.70, capacity:"500 MW", investment:"$10B", status:"Under Construction", year:2026, type:"Hyperscale Colocation", operator:"Compass Datacenters", elecRate:7.1,
    companies: [
      { ticker:"VRT", role:"Power & Cooling Infrastructure", detail:"Thermal management for eight 40MW/250K sqft data center buildings" },
      { ticker:"ETN", role:"Power Distribution", detail:"Switchgear, UPS, and power management across 500 MW phased build" },
      { ticker:"PWR", role:"Electrical Construction", detail:"Substation and transmission line construction for I-20/59 Industrial Park" },
      { ticker:"FIX", role:"HVAC & Mechanical Contractor", detail:"Mechanical cooling systems for 2M+ sqft campus over 8-year build-out" },
      { ticker:"CAT", role:"Backup Power Generation", detail:"Diesel gensets for mission-critical backup across eight-building campus" },
      { ticker:"CMI", role:"Natural Gas Generators", detail:"Prime and backup power generation for Mississippi Power 500 MW supply" },
      { ticker:"FLEX", role:"Modular DC Components", detail:"Anord Mardix critical power distribution and rack CDUs for eight-building 500 MW campus" },
    ]},
  { id:36, name:"Bosque County Campus", state:"TX", lat:31.95, lng:-97.32, capacity:"288 MW", investment:"$4B", status:"Under Construction", year:2026, type:"Hyperscale Colocation", operator:"CyrusOne (KKR/GIP)", elecRate:7.2,
    companies: [
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management for 700K+ sqft two-phase hyperscale campus" },
      { ticker:"ETN", role:"Power Distribution", detail:"Critical power systems for 144 MW Phase 1 and 288 MW Phase 2" },
      { ticker:"EME", role:"Electrical Construction", detail:"Electrical and mechanical build for $1.2B infrastructure investment" },
      { ticker:"CEG", role:"Power Generation (Calpine)", detail:"Calpine subsidiary providing 190 MW from adjacent Thad Hill Energy Center gas plant" },
      { ticker:"GEV", role:"Gas Turbine Solutions", detail:"Behind-the-meter gas generation support for ERCOT grid-connected campus" },
    ]},
  { id:37, name:"Google Virginia Expansion", state:"VA", lat:39.04, lng:-77.49, capacity:"600 MW", investment:"$9B", status:"Under Construction", year:2026, type:"Cloud/AI", operator:"Google", elecRate:7.8,
    companies: [
      { ticker:"GOOGL", role:"Developer & Operator", detail:"$9B expansion across Loudoun, Prince William, and new Chesterfield County campus" },
      { ticker:"AVGO", role:"Custom AI Chip Co-Developer (TPU)", detail:"Co-designs Google TPU silicon with proprietary SerDes IP. Northern Virginia hosts Google's densest cloud footprint" },
      { ticker:"NVDA", role:"GPU Supplier", detail:"GPU clusters for Google Cloud AI infrastructure" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management for multi-campus Northern Virginia expansion" },
      { ticker:"ANET", role:"DC Networking", detail:"400G/800G Ethernet switches for Google Cloud AI cluster interconnect" },
      { ticker:"MRVL", role:"Custom AI Chips & Interconnect", detail:"Custom silicon and data center interconnect for Google's TPU ecosystem" },
      { ticker:"LUMN", role:"Fiber Connectivity", detail:"Private Connectivity Fabric linking Virginia DC campuses to Google's network" },
    ]},
  // ── New projects (Feb 2026 expansion — operator-anchored) ────────────
  { id:38, name:"Polaris Forge 2", state:"ND", lat:46.88, lng:-96.89, capacity:"1 GW", investment:"$3B+", status:"Under Construction", year:2027, type:"GPU Cloud", operator:"Applied Digital", elecRate:7.0,
    companies: [
      { ticker:"APLD", role:"Developer & Operator", detail:"Groundbreaking Sep 2025. 200 MW initial IT load, expandable to 1 GW. $5B 15-year hyperscaler lease" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Proprietary waterless closed-loop cooling system for North Dakota campus" },
      { ticker:"ABB", role:"Power Distribution & UPS", detail:"HiPerGuard medium-voltage UPS infrastructure for phased GW-scale build" },
      { ticker:"CAT", role:"Backup Power Generation", detail:"Standby diesel generators for mission-critical hyperscale campus" },
      { ticker:"OWL", role:"Infrastructure Financing", detail:"Macquarie/Blue Owl financing structure for Applied Digital AI factory portfolio" },
    ]},
  { id:39, name:"Delta Forge 1", state:"TX", lat:31.0, lng:-96.5, capacity:"430 MW", investment:"$2B+", status:"Under Construction", year:2027, type:"GPU Cloud", operator:"Applied Digital", elecRate:7.2,
    companies: [
      { ticker:"APLD", role:"Developer & Operator", detail:"Broke ground Jan 2026. 300 MW critical IT load across two 150 MW buildings on 500+ acres. Undisclosed hyperscaler tenant" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management for two-building AI factory campus" },
      { ticker:"ETN", role:"Power Distribution", detail:"UPS and switchgear for phased 430 MW capacity" },
      { ticker:"STRL", role:"Site Development", detail:"Civil construction and site preparation for 500+ acre greenfield campus" },
    ]},
  { id:40, name:"Equinix xScale Hampton", state:"GA", lat:33.0, lng:-83.8, capacity:"240 MW", investment:"$2.5B", status:"Under Construction", year:2027, type:"Hyperscale Colocation", operator:"Equinix", elecRate:6.9,
    companies: [
      { ticker:"EQIX", role:"Developer & Operator", detail:"First US xScale campus. 262 acres, 4 buildings x 60 MW. Part of $15B GIC/CPP JV" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management for four-building 240 MW hyperscale campus" },
      { ticker:"ETN", role:"Power Distribution", detail:"Switchgear and UPS for phased 60 MW building energization" },
      { ticker:"BE", role:"On-Site Fuel Cell Power", detail:"Bloom Energy fuel cell deployments for behind-the-meter DC generation at Equinix facilities" },
      { ticker:"OKLO", role:"Nuclear Power Partnership", detail:"500 MW nuclear PPA partnership with Equinix for carbon-free behind-the-meter power" },
    ]},
  { id:41, name:"Digital Realty Digital Dulles", state:"VA", lat:38.65, lng:-77.10, capacity:"1 GW", investment:"$7B+ JV", status:"Under Construction", year:2028, type:"Hyperscale Colocation", operator:"Digital Realty", elecRate:9.0,
    companies: [
      { ticker:"DLR", role:"Developer & Operator", detail:"424-acre campus, up to 14 buildings (96-144 MW each). $236M land acquisition. First building delivered 2023, 15-year buildout" },
      { ticker:"VRT", role:"Cooling Infrastructure", detail:"Thermal management for Northern Virginia mega-campus phased build" },
      { ticker:"SBGSY", role:"Electrical Infrastructure", detail:"Power distribution and building management for multi-building campus" },
      { ticker:"HUBB", role:"Electrical Distribution", detail:"Switchgear, transformers, and busbar distribution for phased GW-scale build" },
      { ticker:"POWL", role:"Switchgear & Power Control", detail:"Custom medium-voltage switchgear for on-site substations serving 1 GW campus" },
      { ticker:"PRY", role:"Power & Fiber Cables", detail:"Power cables and fiber-optic infrastructure for 14-building mega-campus" },
    ]},
];

// ═══════════════════════════════════════════════════════════════════════
//  Development-time referential integrity check
// ═══════════════════════════════════════════════════════════════════════
if (typeof window !== 'undefined' && import.meta.env?.DEV) {
  const referencedTickers = new Set();
  // Forward: project → company
  PROJECTS.forEach(p => {
    p.companies.forEach(c => {
      if (!COMPANIES[c.ticker]) {
        console.error(`[dc-data] Project "${p.name}" (id:${p.id}) references unknown ticker "${c.ticker}"`);
      }
      referencedTickers.add(c.ticker);
    });
  });
  // Reverse: validate tier field and linkage consistency
  Object.entries(COMPANIES).forEach(([ticker, co]) => {
    if (!co.tier) console.warn(`[dc-data] Company "${ticker}" missing tier field`);
    if (co.tier === "direct" && !referencedTickers.has(ticker)) {
      console.error(`[dc-data] Direct-tier company "${ticker}" (${co.name}) not referenced by any project`);
    }
    if (co.tier === "upstream" && referencedTickers.has(ticker)) {
      console.warn(`[dc-data] Upstream company "${ticker}" appears in project linkages — should it be tier:"direct"?`);
    }
  });
}
